service: nodejs-aws-lambda-mongo
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs18.x
  environment:
    ${file(env.json)}
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
     
     