service: nodejs-aws-lambda-mongo
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs18.x
  environment:
    ${file(env.json)}
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
