import room2 from "../assets/room2.jpg";
import room1 from "../assets/room1.jpg";
import room3 from "../assets/room3.jpg";
import room4 from "../assets/room4.jpg";
import uuid from "react-uuid";

export const roomsList = [
  {
    id: uuid(),
    title: "Queen Bed A-12324",
    image: room1,
    room_type: "Single Bed",
    room_number: 10,
    amenities: [
      { a_name: "wifi", icon: "wifi" },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      {a_name: "towels", icon: "towels"},
      {a_name: "shop_near", icon: "shop_near"},
      {a_name: "cleaning", icon: "cleaning"},
      {a_name: "breakfast", icon: "breakfast"},
      {a_name: "kitchen", icon: "kitchen"},
      {a_name: "shower", icon: "shower"},
    ],
    price: 245,
    discount: 10,
    offer: "yes",
    offer_price: 145,
    description: "Beautiful and cozy room ",
    cancellation: "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable",
  },
  {
    id: uuid(),
    title: "Classic Double Bed B-12324",
    image: room2,
    room_type: "Double Bed",
     room_number: 3,
    amenities: [
      { a_name: "wifi", icon: "wifi" },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      {a_name: "towels", icon: "towels"},
      {a_name: "shop_near", icon: "shop_near"},
      {a_name: "cleaning", icon: "cleaning"},
      {a_name: "breakfast", icon: "breakfast"},
      {a_name: "kitchen", icon: "kitchen"},
      {a_name: "shower", icon: "shower"},
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 245,
    description: "Beautiful and cozy room ",
    cancellation: "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Booked"
  },
  {
    id: uuid(),
    title: "Luxury Room  D-1231",
    image: room3,
    room_type: "Double Superior",
     room_number: 2,
    amenities: [
      { a_name: "wifi", icon: "wifi" },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      {a_name: "towels", icon: "towels"},
      {a_name: "shop_near", icon: "shop_near"},
      {a_name: "cleaning", icon: "cleaning"},
      {a_name: "breakfast", icon: "breakfast"},
      {a_name: "kitchen", icon: "kitchen"},
      {a_name: "shower", icon: "shower"},
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 300,
    description: "Beautiful and cozy room ",
    cancellation: "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable"
  },
  {
    id: uuid(),
    title: "Luxury Suite Room  X-1342",
    image: room4,
    room_type: "Suite",
     room_number: 5,
    amenities: [
      { a_name: "wifi", icon: "wifi" },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      {a_name: "towels", icon: "towels"},
      {a_name: "shop_near", icon: "shop_near"},
      {a_name: "cleaning", icon: "cleaning"},
      {a_name: "breakfast", icon: "breakfast"},
      {a_name: "kitchen", icon: "kitchen"},
      {a_name: "shower", icon: "shower"},
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 300,
    description: "Beautiful and cozy room ",
    cancellation: "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable",
    
  },
   {
    id: uuid(),
    title: "Queen Bed A-12324",
    image: room1,
    room_type: "Single Bed",
    room_number: 10,
    amenities: [
      { a_name: "wifi", icon: "wifi" },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      {a_name: "towels", icon: "towels"},
      {a_name: "shop_near", icon: "shop_near"},
      {a_name: "cleaning", icon: "cleaning"},
      {a_name: "breakfast", icon: "breakfast"},
      {a_name: "kitchen", icon: "kitchen"},
      {a_name: "shower", icon: "shower"},
    ],
    price: 245,
    offer: "yes",
    offer_price: 145,
    cancellation: "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Booked",
    description: "Beautiful and Cozy Room",
  },
  
  
];
